version: '3'
services:
  myapp1:
    image: app
    volumes:
      - ./log/:/log
    networks:
      mynetwork:
  myapp2:
    image: app
    volumes:
      - ./log/:/log
    networks:
      mynetwork:
volumes:
  shared-data:
networks:
  mynetwork:
