version: '3'
services:
  myapp1:
    image: app
    networks:
      mynetwork:

  myapp2:
    image: app
    networks:
      mynetwork:

  myapp3:
    image: app
    networks:
      mynetwork:


networks:
  mynetwork: