version: '3'
services:
  myapp1:
    image: app
    networks:
      mynetwork:
    ports:
      - "5001:5001"
  myapp2:
    image: app
    networks:
      mynetwork:
    ports:
      - "5000:5000"

networks:
  mynetwork: